# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5aa429ca5932c4e9aa30a1a01f082d5ef35e3ab5da89566f8dd1b9cf3f6c910eeee38f5af5f5968453a470f32ed089263c1ef64e291b36c30a1b82eb2f1c7496

test:
  secret_key_base: 5e69def23cbff4ae6a2fb199756395a64eb52323d2cafecb546ce74458c90bc42b259c8b7c6d8ddbe4459ba261e647e321b6f3d6f062d7321d77c63a66b0f635

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
